# Generated by Django 4.1.3 on 2022-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVCKAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(auto_created=True)),
                ('Baslik', models.CharField(max_length=100)),
                ('KapiModeli', models.CharField(max_length=20)),
                ('Aciklama', models.CharField(max_length=150)),
                ('Resim_261', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
                ('Resim_283', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
                ('Resim_284', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
                ('Resim_288', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
                ('Resim_292', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
                ('Resim_294', models.ImageField(blank=True, null=True, upload_to=models.CharField(max_length=100))),
            ],
        ),
    ]
