# Generated by Django 4.1.3 on 2022-11-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_261',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_283',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_284',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_288',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_292',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
        migrations.AlterField(
            model_name='pvckapi',
            name='Resim_294',
            field=models.ImageField(blank=True, null=True, upload_to='Baslik'),
        ),
    ]
